# Generated by Django 4.1.7 on 2023-03-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('subject', models.CharField(max_length=500, verbose_name='Assumpte')),
                ('descripcio', models.CharField(blank=True, max_length=524288, null=True, verbose_name='Descripció')),
                ('tipus', models.CharField(choices=[('B', 'Bug'), ('P', 'Pregunta'), ('M', 'Millora')], default='B', max_length=5, verbose_name='Tipus')),
                ('estat', models.CharField(choices=[('N', 'Nova'), ('D', 'En curs'), ('T', 'Llesta per testejar'), ('C', 'Tancada'), ('I', 'Necessita informació'), ('R', 'Rebutjada'), ('P', 'Proposada')], default='N', max_length=5, verbose_name='Estat')),
                ('gravetat', models.CharField(choices=[('D', 'Desitjada'), ('M', 'Menor'), ('N', 'Normal'), ('I', 'Important'), ('C', 'Crítica')], default='N', max_length=5, verbose_name='Gravetat')),
                ('prioritat', models.CharField(choices=[('B', 'Baixa'), ('M', 'Normal'), ('A', 'Alta')], default='M', max_length=5, verbose_name='Prioritat')),
                ('dataCreacio', models.DateField(auto_now_add=True, verbose_name='Data creació')),
                ('dataModificacio', models.DateField(auto_now=True, verbose_name='Última modificació')),
                ('dataLimit', models.DateField(null=True, verbose_name='Data límit')),
                ('assignacio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignats', to='usuaris.usuari', verbose_name='Assignada a')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creats', to='usuaris.usuari', verbose_name='Creador')),
            ],
        ),
    ]
