# Generated by Django 4.1.7 on 2023-03-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignats', to='usuaris.usuari', verbose_name='Assignada a'),
        ),
        migrations.AddField(
            model_name='issue',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creats', to='usuaris.usuari', verbose_name='Creador'),
        ),
    ]
