# Generated by Django 4.1.7 on 2023-03-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignats', to='usuaris.usuari', verbose_name='Assignada a'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='dataLimit',
            field=models.DateField(blank=True, null=True, verbose_name='Data límit'),
        ),
    ]
