# Generated by Django 4.1.7 on 2023-03-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creats', to='usuaris.usuari', verbose_name='Creador'),
        ),
    ]
