# Generated by Django 4.1.7 on 2023-03-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='dataCreacio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creació'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='dataLimit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data límit'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='dataModificacio',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificació'),
        ),
    ]
