# Generated by Django 4.1.7 on 2023-04-01 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_datacreacio_alter_issue_datalimit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('nom', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nom')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$')], verbose_name='Color')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='issues.tag', verbose_name='Tags'),
        ),
    ]
