# Generated by Django 4.1.7 on 2023-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_tag_issue_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bloquejat',
            field=models.BooleanField(default=False, verbose_name='Bloquejat'),
        ),
        migrations.AddField(
            model_name='issue',
            name='motiuBloqueig',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motiu bloqueig'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(to='issues.tag', verbose_name='Tags'),
        ),
    ]
