# Generated by Django 4.1.7 on 2023-04-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue', verbose_name='Issue'),
        ),
    ]
