# Generated by Django 4.1.7 on 2023-04-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_usuari_bio'),
        ('issues', '0008_alter_attachment_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000, verbose_name='Text')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data publicació')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris', to='usuaris.usuari', verbose_name='Autor')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris', to='issues.issue', verbose_name='Issue')),
            ],
        ),
    ]
