# Generated by Django 4.1.7 on 2023-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_comentari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(related_name='issues', to='issues.tag', verbose_name='Tags'),
        ),
    ]
