# Generated by Django 4.1.7 on 2023-04-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_usuari_bio'),
        ('issues', '0010_alter_issue_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='observadors',
            field=models.ManyToManyField(related_name='observats', to='usuaris.usuari', verbose_name='Observadors'),
        ),
    ]
