# Generated by Django 4.1.7 on 2023-04-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0006_alter_usuari_avatar'),
        ('issues', '0011_issue_observadors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data creació')),
                ('tipus', models.CharField(choices=[], max_length=20, verbose_name='Tipus')),
                ('valor_previ', models.CharField(blank=True, max_length=524288, null=True, verbose_name='Valor previ')),
                ('valor_nou', models.CharField(blank=True, max_length=524288, null=True, verbose_name='Valor nou')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='issues.issue', verbose_name='Issue')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='usuaris.usuari', verbose_name='Usuari')),
            ],
        ),
    ]
