# Generated by Django 4.1.7 on 2023-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tipus',
            field=models.CharField(max_length=20, verbose_name='Tipus'),
        ),
    ]
