# Generated by Django 4.1.7 on 2023-04-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_alter_log_issue_alter_log_usuari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tipus',
            field=models.CharField(choices=[('Assumpte', 'Assumpte'), ('Descripció', 'Descripció'), ('Tipus', 'Tipus'), ('Estat', 'Estat'), ('Gravetat', 'Gravetat'), ('Prioritat', 'Prioritat'), ('Assignada a', 'Assignada a'), ('Data límit', 'Data límit'), ('Bloquejat', 'Bloquejat'), ('Creada', 'Creada'), ('Nou attachment', 'Nou attachment'), ('Attachment esborrat', 'Attachment esborrat'), ('Tag afegida', 'Tag afegida'), ('Tag esborrada', 'Tag esborrada')], max_length=20, verbose_name='Tipus'),
        ),
    ]
