# Generated by Django 4.1.7 on 2023-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_alter_attachment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to='', verbose_name='Document'),
        ),
    ]
