# Generated by Django 4.1.7 on 2023-04-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_alter_attachment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='issues.issue', verbose_name='Issue'),
        ),
    ]
