# Generated by Django 4.1.7 on 2023-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nom dusuari')),
            ],
        ),
    ]
