# Generated by Django 4.1.7 on 2023-04-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='bio',
            field=models.CharField(blank=True, max_length=210, null=True, verbose_name='Bio'),
        ),
    ]
