# Generated by Django 4.1.7 on 2023-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0004_alter_usuari_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='avatar',
            field=models.FileField(default='https://issuestorage.s3.us-west-2.amazonaws.com/media/avatar/default.png', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
