# Generated by Django 4.1.7 on 2023-04-05 17:00

from django.db import migrations, models
import issuePeople.backends


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0006_alter_usuari_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='avatar',
            field=models.FileField(default='https://issuestorage.s3.us-west-2.amazonaws.com/media/avatar/default.png', storage=issuePeople.backends.MediaStorage(), upload_to='avatar/', verbose_name='Avatar'),
        ),
    ]
