# Generated by Django 4.1.7 on 2023-04-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0008_alter_usuari_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='avatar',
            field=models.FileField(default='default.png', upload_to='avatar/', verbose_name='Avatar'),
        ),
    ]
